### ISSUE TITLE
Add README and Templates

### ISSUE THREAD

**Issue by titaniumbones** [archivers-space/archivers-api#5] opened 2017-10-26 01:28 UTC
Make sure this repo has the following files:
- [ ] Readme `README.md`
   - [ ] Repo Badges for: Github Project, Slack, License
   - [ ] 1-3 sentence description of repository contents
   - [ ] Getting Involved section
   - [ ] Development section
- [ ] License -- `LICENSE`
- [ ] Contributing Guidelines (minimal and pointing to org-wide) `.github/CONTRIBUTING.md`
- [ ] Issue Template -- `.github/ISSUE_TEMPLATE.md`
- [ ] GitHub Description from 1-3 sentence readme blurb

This issue forms part of [a project-wide meta-issue](https://github.com/datatogether/roadmap/issues/37)

**Comment by dcwalk** [comment] 2017-10-26 02:10
This is a duplicate of #4 , closing

**Closed as completed by dcwalk** 2017-10-26 02:10 UTC
Labels: duplicate, doc-sprint
